[package]
name = "fair_perf_ml"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "fair_perf_ml"
crate-type = ["cdylib"]

[dependencies]
chrono = { version = "0.4.42", features = ["serde"] }
numpy = "0.24.0"
pyo3 = {version = "0.24.0", features = ["extension-module", "chrono"]}
rust-numpy = "0.1.0"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.134"
uuid = {version = "1.18.1", features = ["v4"]}
